### ISSUE TITLE
无法添加影片，设置中天数修改无效。

### ISSUE THREAD

**Issue by bolan716** [4evergaeul/JAV_MovieManager#1]
你好~经过尝试后发现可能和刮削软件有关，之前的影片都是用Movie_Data_Capture刮削的，添加不了，用MDCx的可以添加但不显示图片。

![屏幕截图 2024-07-07 141636](https://github.com/4evergaeul/JAV_MovieManager/assets/29177242/ab4ecfd4-692d-40f9-8ba0-cfdf1ad0c65d)
![屏幕截图 2024-07-07 140939](https://github.com/4evergaeul/JAV_MovieManager/assets/29177242/c78d36b4-d2ad-4b52-8c46-af31ac3a7698)
![无标题](https://github.com/4evergaeul/JAV_MovieManager/assets/29177242/f9522c36-ef4d-4306-9d03-f20102b42329)
![屏幕截图 2024-07-07 141623](https://github.com/4evergaeul/JAV_MovieManager/assets/29177242/7eeddf9f-3e8a-44fc-89a0-6a2979ad2956)

**Comment by 4evergaeul** [comment]
我感觉你文件名看起来没问题，感觉像是http-server没找到图片，你在影片界面能显示图片吗？如果不能的话可以在影片界面点击F12，然后给我看下Console的报错么？

**Comment by bolan716** [comment]
不能显示
![屏幕截图 2024-07-08 201755](https://github.com/4evergaeul/JAV_MovieManager/assets/29177242/22b3b14a-f57d-4928-8556-9d8471a37180)

**Comment by 4evergaeul** [comment]
看样子就是http-server的问题，你可以检查一下你http-server是否成功安装吗？
1. 打开cmd，输入并执行 `http-server C:\`，如果执行成功，说明http-server没问题，请试一下重启电脑。
2. 如果执行不成功，请输入并执行`npm install -g http-server`安装。
另外建议下载我最新的release v1.2.1， 我加了更多日志和优化了用户体验。

如果试了上述还是不行的话，请把logs文件夹里最新的log发给我，我看一下能不能分析出原因。

**Comment by bolan716** [comment]
用了最新版还是不显示图片。
[log_20240710220405.txt](https://github.com/user-attachments/files/16163290/log_20240710220405.txt)

**Comment by 4evergaeul** [comment]
加一下telegram吧，可能需要具体看一下你的配置情况… https://t.me/+9JBjtAz_EqhmMmRh

**Comment by bolan716** [comment]
![屏幕截图 2024-07-13 012010](https://github.com/user-attachments/assets/ae317b4c-fe9a-48bb-958b-50999ee8f9d5)

**Comment by 4evergaeul** [comment]
应该是因为片是无码的，数据没加成功，试一下有码的？
