### ISSUE TITLE
无法正常启动MovieManager.TrayApp

### ISSUE THREAD

**Issue by Big-Bang-001** [4evergaeul/JAV_MovieManager#2]
一直卡在初始化界面，安装步骤按项目介绍里逐步操作的。

**Comment by 4evergaeul** [comment]
你好，请试一下打开任务管理器然后找到MovieManager.Tray并强行关闭，然后再次打开试试。

**Comment by Big-Bang-001** [comment]
没有安装在C:\Program Files\有影响吗？

**Comment by Big-Bang-001** [comment]
重启后还是没有效果，显示无响应

**Comment by 4evergaeul** [comment]
Potplayer我建议是放在那个文件夹，但电影管理器无所谓的，另外如果无法启动的话，除了MovieManager.Tray要强行关掉，建议把node.js runtime也关掉

**Comment by 4evergaeul** [comment]
> 重启后还是没有效果，显示无响应

可以去到log文件夹里，把最新的log发我一下吗？另外还可以试下重启电脑

**Comment by Big-Bang-001** [comment]
[log_20240717141809.txt](https://github.com/user-attachments/files/16318880/log_20240717141809.txt)
[log_20240717142205.txt](https://github.com/user-attachments/files/16318881/log_20240717142205.txt)
[log_20240717143040.txt](https://github.com/user-attachments/files/16318882/log_20240717143040.txt)
[log_20240720103922.txt](https://github.com/user-attachments/files/16318883/log_20240720103922.txt)
[log_20240720114523.txt](https://github.com/user-attachments/files/16318884/log_20240720114523.txt)
[log_20240720114837.txt](https://github.com/user-attachments/files/16318885/log_20240720114837.txt)

**Comment by 4evergaeul** [comment]
请试下最新的release

**Comment by Big-Bang-001** [comment]
还是卡在这个app启动

**Comment by 4evergaeul** [comment]
请发一下log

**Comment by Big-Bang-001** [comment]
2024-07-21 20:45:18.108 +08:00 [INF] Application starting up...
2024-07-21 20:45:18.593 +08:00 [INF] Application is setting up...
2024-07-21 20:45:18.593 +08:00 [INF] Starting web app...

全都是这样的

**Comment by 4evergaeul** [comment]
试下这个版本？之前的那版我忘记删除文件读写的一段代码了，如果你没有给程序管理员权限，有可能无法进行文件读写所以才出错。如果还是不行的话，还是发一下log。

https://github.com/4evergaeul/JAV_MovieManager/releases/download/v1.3.2/MovieManager_07262024_101130.zip

**Comment by Big-Bang-001** [comment]
2024-07-26 22:24:32.337 +08:00 [INF] Application starting up...Current Version: JavMovieManager_07262024_1
2024-07-26 22:24:32.974 +08:00 [INF] Application is setting up...
2024-07-26 22:24:32.975 +08:00 [INF] Starting web app...
2024-07-26 22:24:32.975 +08:00 [INF] Trying to start the web app from port number 3000
2024-07-26 22:24:32.976 +08:00 [INF] Starting the web app from port number 3000
2024-07-26 22:24:34.046 +08:00 [INF] App started successfully!

**Comment by Big-Bang-001** [comment]
启动成功了，但是网页显示不了，应用是在防火墙名单内的

**Comment by 4evergaeul** [comment]
你试下这样：打开控制台，cd到movie manager文件夹下build文件夹，然后输入serve，然后从控制台的链接看看能不能打开。

![image](https://github.com/user-attachments/assets/72ca0336-82c8-4a53-af80-e8689fdad34c)

**Comment by Big-Bang-001** [comment]
![Uploading 11.PNG…]()

**Comment by Big-Bang-001** [comment]
不行啊，老哥

**Comment by Big-Bang-001** [comment]
![11](https://github.com/user-attachments/assets/79c348a0-b71d-4621-b53e-e65bb974b01f)

**Comment by 4evergaeul** [comment]
可以这样：` serve "E:\AVguanli\MovieManager_07262024_101130\build"`

**Comment by Big-Bang-001** [comment]
'serve' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by 4evergaeul** [comment]
node.js你装了吧？运行一下这个
npm install --global serve

**Comment by Big-Bang-001** [comment]
npm error code ENOENT
npm error syscall open
npm error path C:\Users\package.json
npm error errno -4058
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: C:\Users\AppData\Local\npm-cache\_logs\2024-07-26T15_01_05_063Z-debug-0.log

**Comment by Big-Bang-001** [comment]
显示错误。。。

**Comment by 4evergaeul** [comment]
试一下重新安装下node,js,（问的chatgpt）
https://nodejs.org/dist/v20.16.0/node-v20.16.0-x64.msi

**Comment by Big-Bang-001** [comment]
算了，还是不行

**Comment by 4evergaeul** [comment]
我把node.js的启动依赖去掉了，有空再试下吧，多谢了。

https://github.com/4evergaeul/JAV_MovieManager/releases/download/v1.4/MovieManager_07262024_011156.zip/

**Comment by Big-Bang-001** [comment]
![55](https://github.com/user-attachments/assets/4e6b668b-1613-4165-97b3-9beefb497ed9)

**Comment by Big-Bang-001** [comment]
已经好了，感谢！

**Comment by 4evergaeul** [comment]
Closing
